### ISSUE TITLE
Integrate a timer for display on/off at definite time

### ISSUE THREAD

**Issue by testpaul999** [roblatour/ESP32RemoteForVictron#1]
**Is your feature request related to a problem? Please describe.**

integrate NTP (configurable) for realtime and an display sleep timer for display off at night.
Regards

**Describe the solution you'd like**

At the secret_settings.h
#define NTP               "xxx.xxx.xxx.xxx"                     // NTP which is on the same network or externally 
#define Sleep_Time  "22:00“                                     //start time for display off in 24h format 
#define Wakeup_Time. "07:00“                                  //end time for display off in 24h format 

**Describe alternatives you've considered**

**Additional context**

**Comment by roblatour** [comment]
sure; I'll take a run at it.

**Comment by roblatour** [comment]
@testpaul999 

ok - now released as version 1.1.  Please update you desired options in the files: general_settings.h and secret_settings.h
