### ISSUE TITLE
Display the Grid over all phases

### ISSUE THREAD

**Issue by testpaul999** [roblatour/ESP32RemoteForVictron#2]
**Is your feature request related to a problem? Please describe.**
Display the Grid over all phases

**Describe the solution you'd like**
I would found it better to see the summary of all phases l1-l2-l3 and not only l1.
So I can see my ess are working fine.

**Describe alternatives you've considered**

**Additional context**
See screenshot form victron
![image](https://github.com/roblatour/ESP32RemoteForVictron/assets/35597907/d7bd1c7a-5970-4640-a55f-c2519175e0b6)
The left red called „Netz“ you will see the summary and this will be „0“ for me.
Screenshot from esp32
![image](https://github.com/roblatour/ESP32RemoteForVictron/assets/35597907/3151d090-8d3b-4dd8-ab9d-07ce7f3c10ee)
You will only see l1

Thx 👍🏻

**Comment by roblatour** [comment]
no problem, it was actually something that was in the code before the original release but I took it out because my own system doesn't use Grid 2 and Grid 3.  Also, AC Load 3 for the same reason. Regardless, I just updated the code so that it would handle all of these.  Enjoy.

**Comment by testpaul999** [comment]
Thx for fast reaction but :-( so issue

[adruino issue.txt](https://github.com/roblatour/ESP32RemoteForVictron/files/15111423/adruino.issue.txt)

**Comment by testpaul999** [comment]
👍🏻
![image](https://github.com/roblatour/ESP32RemoteForVictron/assets/35597907/c9bc59c3-610e-448b-8598-026911548c80)
Great works like expected

**Comment by testpaul999** [comment]
Last wish from my site.
if the two buttons are set to „false“, pls. don’t display this.

**Comment by roblatour** [comment]
Changes made in v1.3 for your last wish as well!   Enjoy.
